services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  django:
    build: .
    container_name: django
    command: /app/.venv/bin/gunicorn --bind 0.0.0.0:8000 --workers 3 api_admin_demo.wsgi:application
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

  celery-worker:
    build: .
    container_name: celery_worker
    command: /app/.venv/bin/celery -A api_admin_demo worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: celery_beat
    command: /app/.venv/bin/celery -A api_admin_demo beat -l info
    depends_on:
      rabbitmq:
        condition: service_healthy
      celery-worker:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
